name: Release

on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    name: Build sdist and wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build

      - name: Build artifacts
        run: |
          python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/*

  publish:
    name: Publish to PyPI (Trusted Publisher)
    needs: build
    runs-on: ubuntu-latest
    # OIDC token is required for PyPI Trusted Publisher
    permissions:
      id-token: write
      contents: read
    environment:
      name: pypi
      url: https://pypi.org/p/depgate
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist-artifacts
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          # Uncomment to allow re-running a release without failing if files exist
          # skip-existing: true

